apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: git@github.com:adilosch/kustomize.git
    targetRevision: main
    hydrator:
      type: kustomize
      outputPath: hydrated/nginx
  syncPolicy:
    automated:
      enabled: true