apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-user-without-acl
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: src
    repoURL: git@github.com:adilosch/kustomize.git
    targetRevision: kafka_user_without_acl
