apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-user3
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: git@github.com:adilosch/kustomize.git
    targetRevision: user3