apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./src/overlays/dev/
    repoURL: git@github.com:adilosch/kubernetes-deployment.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true