apiVersion: v1
data:
  APP_ENV: base
kind: ConfigMap
metadata:
  labels:
    app: my-service1
    env: nop
    x: "y"
  name: nop-myapp-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service1
    env: nop
    x: "y"
  name: nop-service1
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: service1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-service1
    env: nop
    x: "y"
  name: nop-service1
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:3.9r3r3
        name: nginx
        ports:
        - name: http
