apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: my-kafka-chart
    repoURL: git@github.com:adilosch/kustomize.git
    targetRevision: topic_with_acl