{{- $users := .Files.Get .Values.usersFile | fromYaml }}
{{- range $users.kafka.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512  # If using SCRAM authentication
  authorization:
    type: acl  # Use 'acl' type for ACL-based authorization
    acls:
      {{- range .acl }}
      - resource:
          type: topic
          name: {{ .topic }}
        operation: {{ .permissions | join ", " | title }}  # Use 'title' instead of 'capitalize' for proper capitalization
      {{- end }}
---
{{- end }}
