{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafkaCluster }}
spec:
  partitions: {{ .partitions | default 3 }}
  replicas: {{ .replicas | default 2 }}
  config:
    retention.ms: {{ .retentionMs | default 604800000 }}
---
{{- end }}
