# templates/kafka-user.yaml
{{- range $user, $config := .Values.kafkaUsers }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ $user }}
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      {{- range $config.acls }}
      - resource:
          type: {{ .resourceType }}
          name: {{ .resourceName }}
        operation: {{ .operation }}
      {{- end }}
---
{{- end }}
