{{- range .Values.kafka.users }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: plain
  authorization:
    acls:
      {{- range .acl }}
      - resource:
          type: topic
          name: {{ .topic }}
        operation: {{ .permissions | join ", " }}
      {{- end }}
---
{{- end }}
