{{- range .Values.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: {{ default 1 .partitions }}
  replicas: {{ default 1 .replicas }}
  config:
    retention.ms: {{ default 86400000 .retentionMs }}
---
{{- end }}