apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-job
  annotations:
    argocd.argoproj.io/hook: PreDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: cleanup
        image: alpine
        command: ["sh", "-c", "echo 'Running pre-delete cleanup...'"]
      restartPolicy: Never