apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user3
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: example-topic-test-user3
        operation: Read
