apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nop
  namespace: argocd
spec:
  destination:
    namespace: nop
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./src/overlays/nop/
    repoURL: git@github.com:adilosch/kustomize.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true